### PR TITLE
Modified SimpleSeq2Seq in order to be able to run it in Keras 2.

### PR DESCRIPTION
**Pull request by nchervyakov**
Maybe this changes shouldn't go  into the repo, but I decided to share my modifications. With this changes I was able to run model training.

For some reasons first Dropout in the decoder failed to work, so I moved it to the final model.

### CODE REVIEW

**Comment by nchervyakov** [comment]
I saw the pull request from @abhaikollara, but his changes does not help me to run the model, I get the following error:
```
Note that input tensors are instantiated via `tensor = Input(shape)`.
The tensor that caused the issue was: recurrent_sequential_2/input_23:0
  str(x.name))
Traceback (most recent call last):
  File "F:/projects/seq2seq/seq2seq/test.py", line 8, in <module>
    model = SimpleSeq2Seq(input_shape=(None, 5), hidden_dim=10, output_length=8, output_dim=11)
  File "F:\projects\seq2seq\seq2seq\models.py", line 93, in SimpleSeq2Seq
    model.add(decoder)
  File "C:\Users\nick_chervyakov.monster\AppData\Local\Dato\DatoLauncher\envs\python3\lib\site-packages\keras\models.py", line 463, in add
    output_tensor = layer(self.outputs[0])
  File "C:\Users\nick_chervyakov.monster\AppData\Local\Dato\DatoLauncher\envs\python3\lib\site-packages\recurrentshop\engine.py", line 440, in __call__
    self.build(K.int_shape(inputs[0]))
  File "C:\Users\nick_chervyakov.monster\AppData\Local\Dato\DatoLauncher\envs\python3\lib\site-packages\recurrentshop\engine.py", line 973, in build
    self.model = Model([input] + initial_states, [output] + final_states)
  File "C:\Users\nick_chervyakov.monster\AppData\Local\Dato\DatoLauncher\envs\python3\lib\site-packages\keras\legacy\interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\nick_chervyakov.monster\AppData\Local\Dato\DatoLauncher\envs\python3\lib\site-packages\keras\engine\topology.py", line 1572, in __init__
    if layer.is_placeholder:
AttributeError: 'Dropout' object has no attribute 'is_placeholder'
```
But with my changes I successfully run the model.

**Comment by abhaikollara** [comment]
@farizrahman4u You should probably merge this, I've already fixed this in my PR #173 , but I'm gonna close that since `models.py` needs to be rewritten

**Comment by abhaikollara** [comment]
@nchervyakov There are still quite a few changes to be made, seq2seq-1 isn't functional as of yet.

**Comment by nchervyakov** [comment]
@abhaikollara, I agree with you, but I haven't touched other models yet, so I cannot PR full changes. I also think that seq2seq-1 should be rewritten, but I didn't master this lib yet, I've just begun with it. I will PR all my additions along the way.

**Comment by nchervyakov** [comment]
@abhaikollara, I also didn't like the way I made dropout and input. As I understand, this features should work as they do in the current code, but they don't. So maybe the problem is also in RecurrentSequential.

**Comment by abhaikollara** [comment]
@nchervyakov The `models.py` will be completely rewritten

**Comment by nchervyakov** [comment]
@abhaikollara, OK, will keep in mind.

**Pull request closed without merging**
