### PR TITLE
Update LSTMDecoder to RecurrentShop-1

### PR DESCRIPTION
**Pull request by abhaikollara**
More changes coming up . . .

### CODE REVIEW

**Comment by farizrahman4u** [comment]
Please make the PRs to Seq2seq-1 branch.

**Comment by abhaikollara** [comment]
Can't find a Seq2Seq-1 branch

**Comment by farizrahman4u** [comment]
Try again.

**Comment by farizrahman4u** [comment]
LGTM, Thanks!

**Pull request merged**
